"""empty message

Revision ID: 38b9cff47cdb
Revises: 2b7380507a71
Create Date: 2023-10-16 07:47:10.547579

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "38b9cff47cdb"
down_revision = "2b7380507a71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "address",
        sa.Column("street", sa.String(length=255), nullable=False),
        sa.Column("number", sa.String(length=255), nullable=False),
        sa.Column("floor", sa.String(length=255), nullable=False),
        sa.Column("door", sa.String(length=255), nullable=False),
        sa.Column("town", sa.String(length=255), nullable=False),
        sa.Column("postal_code", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("gender", sa.String(length=255), nullable=False),
        sa.Column("cpr", sa.String(length=255), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("address", sa.UUID(), nullable=False),
        sa.Column("phone_number", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["address"],
            ["address.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("dummy_model")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dummy_model",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="dummy_model_pkey"),
    )
    op.drop_table("user")
    op.drop_table("address")
    # ### end Alembic commands ###
