version: '3.9'

services:
  api:
    ports:
      # Exposes application port.
    - "8001:8001"
    build:
      target: dev
    volumes:
      # Adds current directory as volume.
    - .:/app/src/
    environment:
      # Enables autoreload.
      DATA_FAKER_RELOAD: "True"
